stages:
- test
- build

test:
  image: golang
  stage: test
  coverage: /coverage:\s*([0-9\.]+)%/
  before_script:
  - go test -i
  script:
  - go test -v -cover ./...

.build: &build
  image: golang
  stage: build
  before_script:
  - go test -i
  script:
  - go build
  artifacts:
    paths:
    - remuxing

.win-build: &win-build
  <<: *build
  variables:
    GOOS: windows
  script:
  - go build -o remuxing.exe
  artifacts:
    paths:
    - remuxing.exe

.mac-build: &mac-build
  <<: *build
  variables:
    GOOS: darwin

build:linux-x64:
  <<: *build

build:mac-x64:
  <<: *mac-build

build:linux-x86:
  <<: *build
  variables:
    GOARCH: '386'

build:windows-x64:
  <<: *win-build

build:windows-x86:
  <<: *win-build
  variables:
    GOARCH: '386'
    GOOS: windows
